kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontendweb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: cont1
          image: nginx
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 10m
---
kind: Service
apiVersion: v1
metadata:
  name: frontendweb-svc
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v1
metadata:
  name: frontend-proj-hpa
spec:
  targetCPUUtilizationPercentage: 50
  minReplicas: 3
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontendweb
